name: Release Please

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  release:
    name: Run
    runs-on: ubuntu-latest

    steps:
      - uses: GoogleCloudPlatform/release-please-action@v4
        if: github.event_name != 'workflow_dispatch'
        id: release-please
        with:
          token: '${{ secrets.GH_BOT_TOKEN }}'
          config-file: .github/release-please-config.json
          manifest-file: .github/release-please-manifest.json

      - uses: actions/checkout@v4
        if: github.event_name == 'workflow_dispatch' || fromJSON(steps.release-please.outputs.releases_created)
        with:
          fetch-depth: 0

      - name: Deploy App
        if: github.event_name == 'workflow_dispatch' || fromJSON(steps.release-please.outputs.releases_created)
        env:
          GITHUB_TOKEN: '${{ secrets.GH_BOT_TOKEN }}'
        run: |
          gh workflow run deploy.yml
